import { EnumTypeCard, type ICard } from '@/types/card.types'

export const CARDS: ICard[] = [
	{
		name: 'HTML',
		mana: 1,
		attack: 1,
		health: 1,
		imageUrl: '/assets/cards/html.png',
	},
	{
		name: 'CSS',
		mana: 1,
		attack: 1,
		health: 2,
		imageUrl: '/assets/cards/css.png',
	},
	{
		name: 'Tailwind CSS',
		mana: 1,
		attack: 2,
		health: 1,
		imageUrl: '/assets/cards/tailwind.png',
	},
	{
		name: 'Webpack',
		mana: 2,
		attack: 2,
		health: 2,
		imageUrl: '/assets/cards/webpack.png',
	},
	{
		name: 'JavaScript',
		mana: 2,
		attack: 3,
		health: 2,
		imageUrl: '/assets/cards/js.png',
	},
	{
		name: 'Vs Code',
		mana: 2,
		attack: 2,
		health: 3,
		imageUrl: '/assets/cards/vs-code.png',
	},
	{
		name: 'Webstorm',
		mana: 2,
		attack: 2,
		health: 3,
		imageUrl: '/assets/cards/webstorm.png',
	},
	{
		name: 'Node.js',
		mana: 3,
		attack: 3,
		health: 4,
		imageUrl: '/assets/cards/node.png',
	},
	{
		name: 'Redux',
		mana: 3,
		attack: 5,
		health: 2,
		imageUrl: '/assets/cards/redux.png',
	},
	{
		name: 'Svelte',
		mana: 3,
		attack: 4,
		health: 3,
		imageUrl: '/assets/cards/svelte.png',
	},
	{
		name: 'Vue',
		mana: 3,
		attack: 1,
		health: 6,
		type: EnumTypeCard.taunt,
		imageUrl: '/assets/cards/vue.png',
	},
	{
		name: 'React',
		mana: 3,
		attack: 2,
		health: 5,
		type: EnumTypeCard.taunt,
		imageUrl: '/assets/cards/react.png',
	},
	{
		name: 'Nginx',
		mana: 4,
		attack: 5,
		health: 4,
		imageUrl: '/assets/cards/nginx.png',
	},
	{
		name: 'Gatsby',
		mana: 4,
		attack: 4,
		health: 5,
		imageUrl: '/assets/cards/gatsby.png',
	},
	{
		name: 'Astro',
		mana: 4,
		attack: 6,
		health: 3,
		imageUrl: '/assets/cards/astro.png',
	},
	{
		name: 'Nuxt.js',
		mana: 4,
		attack: 3,
		health: 6,
		type: EnumTypeCard.taunt,
		imageUrl: '/assets/cards/nuxt.png',
	},
	{
		name: 'TypeScript',
		mana: 5,
		attack: 6,
		health: 4,
		imageUrl: '/assets/cards/ts.png',
	},
	{
		name: 'Next.js',
		mana: 5,
		attack: 7,
		health: 3,
		imageUrl: '/assets/cards/next.png',
	},
	{
		name: 'Prisma',
		mana: 5,
		attack: 4,
		health: 6,
		type: EnumTypeCard.taunt,
		imageUrl: '/assets/cards/prisma.png',
	},
	{
		name: 'ЖЧ',
		mana: 6,
		attack: 8,
		health: 3,
		imageUrl: '/assets/cards/redgroup.png',
	},
	{
		name: 'NH',
		mana: 6,
		attack: 6,
		health: 6,
		imageUrl: '/assets/cards/nest-js.png',
	},
	{
		name: 'СЧ',
		mana: 6,
		attack: 5,
		health: 7,
		type: EnumTypeCard.taunt,
		imageUrl: '/assets/cards/htmllessons_io.png',
	},
]
